[[redirects]]
force = true
from = "/2013*"
status = 301
to = "https://archive-201x.codeursenseine.com/2013/:splat"

[[redirects]]
force = true
from = "/2014*"
status = 301
to = "https://archive-201x.codeursenseine.com/2014/:splat"

[[redirects]]
force = true
from = "/2015*"
status = 301
to = "https://archive-201x.codeursenseine.com/2015/:splat"

[[redirects]]
force = true
from = "/2016*"
status = 301
to = "https://archive-201x.codeursenseine.com/2016/:splat"

[[redirects]]
force = true
from = "/2017*"
status = 301
to = "https://archive-201x.codeursenseine.com/2017/:splat"

[[redirects]]
force = true
from = "/2018*"
status = 301
to = "https://archive-201x.codeursenseine.com/2018/:splat"

[[redirects]]
force = true
from = "/2019*"
status = 301
to = "https://archive-201x.codeursenseine.com/2019/:splat"

[[redirects]]
force = true
from = "/2020*"
status = 301
to = "https://archives-codeurs-en-seine.netlify.app/archive-2020/2020/:splat"

[[redirects]]
force = true
from = "/2021*"
status = 301
to = "https://archives-codeurs-en-seine.netlify.app/archive-2021/2021/:splat"

[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "frame-ancestors 'none'"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
